### ISSUE TITLE
hkml list shows nothing

### ISSUE THREAD

**Issue by honggyukim** [sjp38/hackermail#1]
Hi SeongJae,

I've just come across this repo and try to use it, but I see nothing is shown following the command sequence in the `README.md`.
```
$ ./hkml init --manifest ./manifests/lore.js

$ ./hkml list damon --fetch
git clone --mirror https://lore.kernel.org/damon/git/0.git ./.hkm/archives/damon/git/0.git
Cloning into bare repository './.hkm/archives/damon/git/0.git'...
remote: Enumerating objects: 4353, done.
remote: Total 4353 (delta 0), reused 0 (delta 0), pack-reused 4353
Receiving objects: 100% (4353/4353), 4.16 MiB | 328.00 KiB/s, done.
Resolving deltas: 100% (432/432), done.
# 0 mails, 0 threads, 0 new threads
# 0 patches, 0 series

$ ./hkml list
# 0 mails, 0 threads, 0 new threads
# 0 patches, 0 series
```
Is there anything I should do more?

**Comment by sjp38** [comment]
Hi Honggyu,


Thank you for opening this issue.  The command receives the `--since` option, allowing users to specify how old mails they want to list.  And, the default value of the option is three days before.  Therefore the command would try to list mails sent to DAMON mailing list within the last three days.

Seems there was no new mail to the mailing list for last three days, and hence the command shows nothing for now.  You could set `--since` old enough.  E.g., `./hkml list damon --fetch --since 2023-12-01`

For testing, you could also try more busy mailing lists such as `linux-mm` or `lkml`.

**Comment by honggyukim** [comment]
Hi SeongJae,

As mentioned offline, it now works fine with `linux-mm`. Thanks for building useful tools!
