### ISSUE TITLE
Adding a patch on reply

### ISSUE THREAD

**Issue by marcosps** [sjp38/hackermail#6]
Is it possible to add another patch as attachment when replying? I couldn't find a way =/

Thanks!

**Comment by sjp38** [comment]
Hi Marcos,


In short, hkml doesn't support attaching files for now.  That's mainly because the tool uses `git send-email` internally, but also because my workflow doesn't need such a feature.  Could you explain your workflow that requires such a feature?

Let me explain my workflow, too, for situations that might be similar to yours.  I sometimes feel it would be nice to send proof-of-concepts patches together with normal discussions about ideas.

In such cases, I usually paste the patch or diff on the body of the mail when it is just for further discussion.  For example,

```
Below is the example patchset of my idea.

==================== 8< ======================
From: Foo Bar <foo.bar@baz.com>
[...]
```

If I feel that makes the size of the mail too big, I post a reply explaining my discussion point and explaining I will send the patch as a reply, and send the patch as a reply to the mail.  For example,

```
So, my idea is as below.
[...]
I will send a patch of this idea as a reply to this mail for reference.
```

If above workaround also works for you, I think we could extend `hkml` to better support such usage.  e.g.,
```
hkml reply X --paste-on-body foo.patch
```

or,

```
hkml reply X --reply-to-reply foo.patch
```

**Comment by marcosps** [comment]
Well, what I did right now is attaching the patch in the body in the email. I believe that it may be nice to have the --paste-on-body, but please don't implement such feature only for me. Also, it's not something that I do everyday, so feel free to ignore :)

**Comment by sjp38** [comment]
Thank you for enlightening me, Marcos!  I think the feature will also be helpful for me, so I will add this to the TODO list, and update it here when the implementation is done.  Don't worry, I will do that on my pace :)  Thank you very much for sharing this great idea!

**Comment by sjp38** [comment]
Implemented the feature as `--attach` option, and pushed to the `master` branch.  The option is also supported by `write` and `forward` commands.
